version: '3.8'

services:
  wb-parser-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb-parser-bot
    image: wb-parser-bot:latest
    command: ["python3", "main_bot.py"]
    env_file:
      - .env
    volumes:
      - ./src:/home/wb_user/bot
    restart: on-failure


