"""Add saleobject and officeobject tables

Revision ID: 192266bd83e7
Revises: 2b741b05d1a6
Create Date: 2024-02-27 09:09:45.554227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192266bd83e7'
down_revision: Union[str, None] = '2b741b05d1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officeobject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('office_area', sa.Integer(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('salary_rate', sa.Float(), nullable=True),
    sa.Column('min_wage', sa.Integer(), nullable=True),
    sa.Column('internet', sa.Integer(), nullable=True),
    sa.Column('administration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id')
    )
    op.create_index(op.f('ix_officeobject_id'), 'officeobject', ['id'], unique=False)
    op.create_table('saleobject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sale_count', sa.Integer(), nullable=True),
    sa.Column('return_count', sa.Integer(), nullable=True),
    sa.Column('sale_sum', sa.Integer(), nullable=True),
    sa.Column('return_sum', sa.Integer(), nullable=True),
    sa.Column('proceeds', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('bags_sum', sa.Integer(), nullable=True),
    sa.Column('office_rating', sa.Float(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('office_rating_sum', sa.Integer(), nullable=True),
    sa.Column('supplier_return_sum', sa.Integer(), nullable=True),
    sa.Column('reward_plan', sa.Float(), nullable=True),
    sa.Column('salary_fund_plan', sa.Float(), nullable=True),
    sa.Column('actual_salary_fund', sa.Float(), nullable=True),
    sa.Column('difference_salary_fund', sa.Float(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('administration', sa.Integer(), nullable=True),
    sa.Column('internet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saleobject_id'), 'saleobject', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saleobject_id'), table_name='saleobject')
    op.drop_table('saleobject')
    op.drop_index(op.f('ix_officeobject_id'), table_name='officeobject')
    op.drop_table('officeobject')
    # ### end Alembic commands ###
