"""make created_at index and office_id index together

Revision ID: 446dbb27c428
Revises: f1ee703264cc
Create Date: 2024-06-26 13:02:52.614962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446dbb27c428'
down_revision: Union[str, None] = 'f1ee703264cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_officeratingobject_created_at'), 'officeratingobject', ['created_at'], unique=False)
    op.create_unique_constraint('uq_office_rating', 'officeratingobject', ['office_id', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_office_rating', 'officeratingobject', type_='unique')
    op.drop_index(op.f('ix_officeratingobject_created_at'), table_name='officeratingobject')
    # ### end Alembic commands ###
