"""empty message

Revision ID: 5d857f1d71be
Revises: 8463e7e99e71
Create Date: 2024-10-14 10:46:43.773605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d857f1d71be'
down_revision: Union[str, None] = '8463e7e99e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saleobject', sa.Column('rate_by_region', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saleobject', 'rate_by_region')
    # ### end Alembic commands ###
