"""Add office_speed_sum field to SaleObject

Revision ID: 84153a08c3db
Revises: c14acaa13ef7
Create Date: 2024-02-29 15:13:42.637241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84153a08c3db'
down_revision: Union[str, None] = 'c14acaa13ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saleobject', sa.Column('office_speed_sum', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saleobject', 'office_speed_sum')
    # ### end Alembic commands ###
