"""Remove unique office_id

Revision ID: 8463e7e99e71
Revises: 446dbb27c428
Create Date: 2024-06-27 07:45:30.375260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8463e7e99e71'
down_revision: Union[str, None] = '446dbb27c428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_officeratingobject_office_id', table_name='officeratingobject')
    op.create_index(op.f('ix_officeratingobject_office_id'), 'officeratingobject', ['office_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officeratingobject_office_id'), table_name='officeratingobject')
    op.create_index('ix_officeratingobject_office_id', 'officeratingobject', ['office_id'], unique=True)
    # ### end Alembic commands ###
