"""Add name to OfficeObject

Revision ID: afa9f3aca061
Revises: 84153a08c3db
Create Date: 2024-03-06 07:54:20.582700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa9f3aca061'
down_revision: Union[str, None] = '84153a08c3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officeobject', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officeobject', 'name')
    # ### end Alembic commands ###
