"""Updated SaleObject model

Revision ID: c14acaa13ef7
Revises: 192266bd83e7
Create Date: 2024-02-28 04:35:37.858185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14acaa13ef7'
down_revision: Union[str, None] = '192266bd83e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saleobject', sa.Column('maintenance', sa.Float(), nullable=True))
    op.add_column('saleobject', sa.Column('profitability', sa.Float(), nullable=True))
    op.alter_column('saleobject', 'administration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('saleobject', 'internet',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saleobject', 'internet',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('saleobject', 'administration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('saleobject', 'profitability')
    op.drop_column('saleobject', 'maintenance')
    # ### end Alembic commands ###
