"""empty message

Revision ID: e11ac7c90b48
Revises: efbd848c3310
Create Date: 2024-06-26 07:02:47.852535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11ac7c90b48'
down_revision: Union[str, None] = 'efbd848c3310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_officeratingobject_office_id'), 'officeratingobject', ['office_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officeratingobject_office_id'), table_name='officeratingobject')
    # ### end Alembic commands ###
