"""Add SaleObject Table

Revision ID: ec308052fd0f
Revises: 2b741b05d1a6
Create Date: 2024-02-20 07:06:55.441322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec308052fd0f'
down_revision: Union[str, None] = '2b741b05d1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saleobject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sale_count', sa.Integer(), nullable=True),
    sa.Column('return_count', sa.Integer(), nullable=True),
    sa.Column('sale_sum', sa.Integer(), nullable=True),
    sa.Column('return_sum', sa.Integer(), nullable=True),
    sa.Column('proceeds', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('bags_sum', sa.Integer(), nullable=True),
    sa.Column('office_rating', sa.Float(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('office_rating_sum', sa.Integer(), nullable=True),
    sa.Column('supplier_return_sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saleobject_id'), 'saleobject', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saleobject_id'), table_name='saleobject')
    op.drop_table('saleobject')
    # ### end Alembic commands ###
