"""empty message

Revision ID: efbd848c3310
Revises: 84bc6682f410
Create Date: 2024-06-26 06:55:04.518398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbd848c3310'
down_revision: Union[str, None] = '84bc6682f410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officeratingobject', sa.Column('office_name', sa.String(), nullable=True))
    op.add_column('officeratingobject', sa.Column('avg_hours', sa.Float(), nullable=True))
    op.add_column('officeratingobject', sa.Column('inbox_count', sa.Integer(), nullable=True))
    op.add_column('officeratingobject', sa.Column('limit_delivery', sa.Integer(), nullable=True))
    op.add_column('officeratingobject', sa.Column('total_count', sa.Integer(), nullable=True))
    op.add_column('officeratingobject', sa.Column('workload', sa.Float(), nullable=True))
    op.drop_column('officeratingobject', 'office_avg_hours')
    op.drop_column('officeratingobject', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officeratingobject', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('officeratingobject', sa.Column('office_avg_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('officeratingobject', 'workload')
    op.drop_column('officeratingobject', 'total_count')
    op.drop_column('officeratingobject', 'limit_delivery')
    op.drop_column('officeratingobject', 'inbox_count')
    op.drop_column('officeratingobject', 'avg_hours')
    op.drop_column('officeratingobject', 'office_name')
    # ### end Alembic commands ###
