"""Add table OfficeRatingObject

Revision ID: f1ee703264cc
Revises: 94c08ee5ba68
Create Date: 2024-06-26 09:33:15.780766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ee703264cc'
down_revision: Union[str, None] = '94c08ee5ba68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officeratingobject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('office_name', sa.String(), nullable=True),
    sa.Column('avg_hours', sa.Float(), nullable=True),
    sa.Column('avg_hours_by_region', sa.Float(), nullable=True),
    sa.Column('avg_rate', sa.Float(), nullable=True),
    sa.Column('avg_region_rate', sa.Float(), nullable=True),
    sa.Column('inbox_count', sa.Integer(), nullable=True),
    sa.Column('limit_delivery', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('workload', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officeratingobject_id'), 'officeratingobject', ['id'], unique=False)
    op.create_index(op.f('ix_officeratingobject_office_id'), 'officeratingobject', ['office_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officeratingobject_office_id'), table_name='officeratingobject')
    op.drop_index(op.f('ix_officeratingobject_id'), table_name='officeratingobject')
    op.drop_table('officeratingobject')
    # ### end Alembic commands ###
